apiVersion: v1
kind: Service
metadata:
  name: eventapp-service
spec:
  type: NodePort
  selector:
    app: eventapp
  ports:
    - port: 80            # cluster-internal port
      targetPort: 8000    # container port
      nodePort: 30080     # access from host: minikube_ip:30080
